<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Catalog\ShopForge.Catalog\ShopForge.Catalog.csproj" />
    <ProjectReference Include="..\..\src\Modules\Orders\ShopForge.Orders\ShopForge.Orders.csproj" />
    <ProjectReference Include="..\..\src\Modules\Stores\ShopForge.Stores\ShopForge.Stores.csproj" />
    <ProjectReference Include="..\..\src\ShopForge.Infrastructure\ShopForge.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\ShopForge.Shared\ShopForge.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
