// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopForge.Infrastructure.Persistence;

#nullable disable

namespace ShopForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShopForgeDbContext))]
    [Migration("20260919085341_AddStoreLogo")]
    partial class AddStoreLogo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopForge.Access.Domain.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_users_email");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_users_tenant_id");

                    b.ToTable("tenant_users", "access", t =>
                        {
                            t.HasCheckConstraint("ck_tenant_users_email_normalized", "email = lower(btrim(email))");
                        });
                });

            modelBuilder.Entity("ShopForge.Catalog.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasAlternateKey("StoreId", "Id")
                        .HasName("ak_categories_store_id_id");

                    b.HasIndex("StoreId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_store_id_slug");

                    b.ToTable("categories", "catalog");
                });

            modelBuilder.Entity("ShopForge.Catalog.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ean")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("ean");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("WeightGrams")
                        .HasColumnType("integer")
                        .HasColumnName("weight_grams");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("TenantId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_products_tenant_id_sku");

                    b.ToTable("products", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_products_weight_grams", "weight_grams IS NULL OR weight_grams >= 0");
                        });
                });

            modelBuilder.Entity("ShopForge.Catalog.Domain.ProductCategory", b =>
                {
                    b.Property<Guid>("StoreProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_product_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.HasKey("StoreProductId", "CategoryId")
                        .HasName("pk_product_categories");

                    b.HasIndex("StoreId", "CategoryId")
                        .HasDatabaseName("ix_product_categories_store_id_category_id");

                    b.HasIndex("StoreId", "StoreProductId")
                        .HasDatabaseName("ix_product_categories_store_id_store_product_id");

                    b.ToTable("product_categories", "catalog");
                });

            modelBuilder.Entity("ShopForge.Catalog.Domain.StoreProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.HasKey("Id")
                        .HasName("pk_store_products");

                    b.HasAlternateKey("StoreId", "Id")
                        .HasName("ak_store_products_store_id_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_store_products_product_id");

                    b.HasIndex("StoreId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_store_products_store_id_product_id");

                    b.HasIndex("StoreId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_store_products_store_id_slug");

                    b.ToTable("store_products", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_store_products_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("ShopForge.Stores.Domain.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("culture");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("LogoPath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("logo_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Theme", "ShopForge.Stores.Domain.Store.Theme#StoreTheme", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("BorderRadius");

                            b1.Property<string>("PrimaryColor")
                                .IsRequired();

                            b1.Property<string>("SecondaryColor")
                                .IsRequired();

                            b1
                                .ToJson("theme")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_stores");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_stores_tenant_id");

                    b.ToTable("stores", "stores", t =>
                        {
                            t.HasCheckConstraint("ck_stores_currency", "currency ~ '^[A-Z]{3}$'");
                        });
                });

            modelBuilder.Entity("ShopForge.Stores.Domain.StoreDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("host_name");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.HasKey("Id")
                        .HasName("pk_store_domains");

                    b.HasIndex("HostName")
                        .IsUnique()
                        .HasDatabaseName("ix_store_domains_host_name");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("ix_store_domains_store_id");

                    b.HasIndex(new[] { "StoreId" }, "ix_store_domains_store_id_primary")
                        .IsUnique()
                        .HasDatabaseName("ix_store_domains_store_id_primary")
                        .HasFilter("is_primary");

                    b.ToTable("store_domains", "stores", t =>
                        {
                            t.HasCheckConstraint("ck_store_domains_host_name_normalized", "host_name = lower(host_name) AND host_name !~ '[:/\\s]'");
                        });
                });

            modelBuilder.Entity("ShopForge.Stores.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", "stores");
                });

            modelBuilder.Entity("ShopForge.Catalog.Domain.Product", b =>
                {
                    b.OwnsMany("ShopForge.Catalog.Domain.ProductImage", "Images", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AltText")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("alt_text");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("content_type");

                            b1.Property<string>("FilePath")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("file_path");

                            b1.Property<int>("Position")
                                .HasColumnType("integer")
                                .HasColumnName("position");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.HasKey("Id")
                                .HasName("pk_product_images");

                            b1.HasIndex("ProductId")
                                .HasDatabaseName("ix_product_images_product_id");

                            b1.ToTable("product_images", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_product_images_products_product_id");
                        });

                    b.Navigation("Images");
                });

            modelBuilder.Entity("ShopForge.Catalog.Domain.ProductCategory", b =>
                {
                    b.HasOne("ShopForge.Catalog.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("StoreId", "CategoryId")
                        .HasPrincipalKey("StoreId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_categories_categories_store_id_category_id");

                    b.HasOne("ShopForge.Catalog.Domain.StoreProduct", null)
                        .WithMany("Categories")
                        .HasForeignKey("StoreId", "StoreProductId")
                        .HasPrincipalKey("StoreId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_categories_store_products_store_id_store_product_id");
                });

            modelBuilder.Entity("ShopForge.Catalog.Domain.StoreProduct", b =>
                {
                    b.HasOne("ShopForge.Catalog.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_store_products_products_product_id");
                });

            modelBuilder.Entity("ShopForge.Stores.Domain.Store", b =>
                {
                    b.HasOne("ShopForge.Stores.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stores_tenant_tenant_id");
                });

            modelBuilder.Entity("ShopForge.Stores.Domain.StoreDomain", b =>
                {
                    b.HasOne("ShopForge.Stores.Domain.Store", null)
                        .WithMany("Domains")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_store_domains_store_store_id");
                });

            modelBuilder.Entity("ShopForge.Catalog.Domain.StoreProduct", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("ShopForge.Stores.Domain.Store", b =>
                {
                    b.Navigation("Domains");
                });
#pragma warning restore 612, 618
        }
    }
}
