// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopForge.Infrastructure.Persistence;

#nullable disable

namespace ShopForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShopForgeDbContext))]
    partial class ShopForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopForge.Stores.Domain.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("culture");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Theme", "ShopForge.Stores.Domain.Store.Theme#StoreTheme", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("BorderRadius");

                            b1.Property<string>("PrimaryColor")
                                .IsRequired();

                            b1.Property<string>("SecondaryColor")
                                .IsRequired();

                            b1
                                .ToJson("theme")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_stores");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_stores_tenant_id");

                    b.ToTable("stores", "stores", t =>
                        {
                            t.HasCheckConstraint("ck_stores_currency", "currency ~ '^[A-Z]{3}$'");
                        });
                });

            modelBuilder.Entity("ShopForge.Stores.Domain.StoreDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("host_name");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.HasKey("Id")
                        .HasName("pk_store_domains");

                    b.HasIndex("HostName")
                        .IsUnique()
                        .HasDatabaseName("ix_store_domains_host_name");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("ix_store_domains_store_id");

                    b.HasIndex(new[] { "StoreId" }, "ix_store_domains_store_id_primary")
                        .IsUnique()
                        .HasDatabaseName("ix_store_domains_store_id_primary")
                        .HasFilter("is_primary");

                    b.ToTable("store_domains", "stores", t =>
                        {
                            t.HasCheckConstraint("ck_store_domains_host_name_normalized", "host_name = lower(host_name) AND host_name !~ '[:/\\s]'");
                        });
                });

            modelBuilder.Entity("ShopForge.Stores.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", "stores");
                });

            modelBuilder.Entity("ShopForge.Stores.Domain.Store", b =>
                {
                    b.HasOne("ShopForge.Stores.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stores_tenant_tenant_id");
                });

            modelBuilder.Entity("ShopForge.Stores.Domain.StoreDomain", b =>
                {
                    b.HasOne("ShopForge.Stores.Domain.Store", null)
                        .WithMany("Domains")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_store_domains_store_store_id");
                });

            modelBuilder.Entity("ShopForge.Stores.Domain.Store", b =>
                {
                    b.Navigation("Domains");
                });
#pragma warning restore 612, 618
        }
    }
}
