<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShopForge.Infrastructure\ShopForge.Infrastructure.csproj" />
    <ProjectReference Include="..\ShopForge.Shared\ShopForge.Shared.csproj" />
    <ProjectReference Include="..\Modules\Access\ShopForge.Access\ShopForge.Access.csproj" />
    <ProjectReference Include="..\Modules\Catalog\ShopForge.Catalog\ShopForge.Catalog.csproj" />
    <ProjectReference Include="..\Modules\Customers\ShopForge.Customers\ShopForge.Customers.csproj" />
    <ProjectReference Include="..\Modules\Inventory\ShopForge.Inventory\ShopForge.Inventory.csproj" />
    <ProjectReference Include="..\Modules\Orders\ShopForge.Orders\ShopForge.Orders.csproj" />
    <ProjectReference Include="..\Modules\Platform\ShopForge.Platform\ShopForge.Platform.csproj" />
    <ProjectReference Include="..\Modules\Stores\ShopForge.Stores\ShopForge.Stores.csproj" />
  </ItemGroup>

</Project>
